export const products = [
  { id: 1, name: 'Laptop', price: 2999, description: 'Nowoczesny laptop do pracy' },
  { id: 2, name: 'Smartwatch', price: 899, description: 'Inteligentny zegarek sportowy' },
  { id: 3, name: 'Słuchawki Bluetooth', price: 399, description: 'Bezprzewodowe słuchawki' },
  { id: 4, name: 'Mysz Bezprzewodowa', price: 149, description: 'Ergonomiczna mysz do pracy' },
  { id: 5, name: 'Klawiatura Mechaniczna', price: 549, description: 'Profesjonalna klawiatura' },
  { id: 6, name: 'Monitor 4K', price: 1899, description: 'Wyświetlacz Ultra HD' },
  { id: 7, name: 'Tablet Samsung', price: 1499, description: 'Tablet 10 cali z ekranem AMOLED' },
  { id: 8, name: 'Kamera internetowa', price: 299, description: 'Full HD kamera do wideokonferencji' },
  { id: 9, name: 'Głośnik Bluetooth', price: 249, description: 'Przenośny głośnik stereo' },
  { id: 10, name: 'Power Bank 20000mAh', price: 129, description: 'Szybka ładowarka do urządzeń' },
  { id: 11, name: 'Kabel USB-C', price: 49, description: 'Trwały kabel szybkiego ładowania' },
  { id: 12, name: 'Adapter HDMI', price: 39, description: 'Konwerter do starszych monitorów' },
  { id: 13, name: 'Docking Station', price: 349, description: 'Stacja dokująca do laptopa' },
  { id: 14, name: 'Dysk SSD 1TB', price: 399, description: 'Nośnik danych Ultra szybki' },
  { id: 15, name: 'Pamięć RAM 16GB', price: 299, description: 'Dodatkowa pamięć operacyjna' },
  { id: 16, name: 'Wentylator PC', price: 89, description: 'Chłodzenie do obudowy' },
  { id: 17, name: 'Mat do myszy RGB', price: 179, description: 'Podkład z podświetleniem LED' },
  { id: 18, name: 'Huby USB 3.0', price: 79, description: 'Rozdzielacz do 4 portów' },
  { id: 19, name: 'Zestaw Kablii', price: 99, description: 'Komplet przewodów elektronicznych' },
  { id: 20, name: 'Stojak do laptopa', price: 159, description: 'Ergonomiczny stojak ze stopu aluminium' },
  { id: 21, name: 'Uchwytu do telefonu', price: 79, description: 'Uniwersalny uchwyt samochodowy' },
  { id: 22, name: 'Ochrona ekranu', price: 39, description: 'Folia hartowana do smartfona' },
  { id: 23, name: 'Etui do laptopa', price: 129, description: 'Ochronne etui z pianki' },
  { id: 24, name: 'Przewód zasilający', price: 59, description: 'Certyfikowany kabel 3m' },
  { id: 25, name: 'Lampa biurkowa LED', price: 199, description: 'Oświetlenie do pracy z ładowaniem' },
  { id: 26, name: 'Kamera IP', price: 449, description: 'Kamera monitoringu WiFi 1080p' },
  { id: 27, name: 'Notes', price: 20, description: 'Zeszyt do zapisywania notatek' }
]
